using System;
using System.Collections.Generic;

namespace GXPowerCommands.Resources
{
	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	public static class Images
	{
		private static global::Artech.Common.Localization.CachingResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		/// <summary>
		/// Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager
		{
			get
			{
				if (global::System.Object.ReferenceEquals(resourceMan, null)) 
				{
					global::Artech.Common.Localization.CachingResourceManager temp = new global::Artech.Common.Localization.CachingResourceManager("GXPowerCommands.Resources.Images", typeof(Images).Assembly);
					resourceMan = temp;
				}

				return resourceMan;
			}
		}

		/// <summary>
		/// Overrides the current thread's CurrentUICulture property for all resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture 
		{
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		/// <summary>
		/// Returns the System.Drawing.Icon resource corresponding to 'build_run'
		/// </summary>
		public static System.Drawing.Icon build_run
		{
			get
			{
				return (System.Drawing.Icon)ResourceManager.GetObject("build_run", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the System.Drawing.Icon resource corresponding to 'clean'
		/// </summary>
		public static System.Drawing.Icon clean
		{
			get
			{
				return (System.Drawing.Icon)ResourceManager.GetObject("clean", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the System.Drawing.Icon resource corresponding to 'command_prompt'
		/// </summary>
		public static System.Drawing.Icon command_prompt
		{
			get
			{
				return (System.Drawing.Icon)ResourceManager.GetObject("command_prompt", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the System.Drawing.Icon resource corresponding to 'folder_black_window'
		/// </summary>
		public static System.Drawing.Icon folder_black_window
		{
			get
			{
				return (System.Drawing.Icon)ResourceManager.GetObject("folder_black_window", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the System.Drawing.Icon resource corresponding to 'folder_delete'
		/// </summary>
		public static System.Drawing.Icon folder_delete
		{
			get
			{
				return (System.Drawing.Icon)ResourceManager.GetObject("folder_delete", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the System.Drawing.Icon resource corresponding to 'folder_open'
		/// </summary>
		public static System.Drawing.Icon folder_open
		{
			get
			{
				return (System.Drawing.Icon)ResourceManager.GetObject("folder_open", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the System.Drawing.Icon resource corresponding to 'lighting'
		/// </summary>
		public static System.Drawing.Icon lighting
		{
			get
			{
				return (System.Drawing.Icon)ResourceManager.GetObject("lighting", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the System.Drawing.Icon resource corresponding to 'play'
		/// </summary>
		public static System.Drawing.Icon play
		{
			get
			{
				return (System.Drawing.Icon)ResourceManager.GetObject("play", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the System.Drawing.Icon resource corresponding to 'rebuild'
		/// </summary>
		public static System.Drawing.Icon rebuild
		{
			get
			{
				return (System.Drawing.Icon)ResourceManager.GetObject("rebuild", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the System.Drawing.Icon resource corresponding to 'trash'
		/// </summary>
		public static System.Drawing.Icon trash
		{
			get
			{
				return (System.Drawing.Icon)ResourceManager.GetObject("trash", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the System.Drawing.Icon resource corresponding to 'tree'
		/// </summary>
		public static System.Drawing.Icon tree
		{
			get
			{
				return (System.Drawing.Icon)ResourceManager.GetObject("tree", resourceCulture);
			}
		}

		/// <summary>
		/// Returns the System.Drawing.Icon resource corresponding to 'variable'
		/// </summary>
		public static System.Drawing.Icon variable
		{
			get
			{
				return (System.Drawing.Icon)ResourceManager.GetObject("variable", resourceCulture);
			}
		}
	}
}